language: php

sudo: false

php:
  - 5.5
  - 5.6

before_script:
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-add travis.php.ini; fi
  - source travis.sh
  - xdebug-disable
  - composer self-update
  - composer update --prefer-source

script:
  - xdebug-enable
  - vendor/bin/phpunit

after_script:
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.2)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token:
      secure: sbJPcBQJVikQCaw20eEoerGf9kxa3In8cJSo8pSyXe1ybtCTF25ZgiyHdN4JegGrMrqtT2iQMkjyOc+1tCN2O7bCH77SlXGQ4wjXpRrY9xoKXZMEc7gBamdC2ViIMeC6BvOSytaaXCn7MPoGweAoQJh6zl5Y8Sc4ZH+p4ZoSldc=
